# Generated by Django 5.2.4 on 2025-07-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indiceinflacion',
            old_name='Mes',
            new_name='Fecha',
        ),
    ]
