# Generated by Django 5.2.4 on 2025-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_rename_mes_indiceinflacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceinflacion',
            name='Fecha',
            field=models.CharField(unique=True),
        ),
    ]
