# Generated by Django 5.2.4 on 2025-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion_Propiedad', models.CharField()),
                ('Dueno', models.CharField()),
                ('Inquilino', models.CharField()),
                ('Fecha_contrato', models.DateField()),
                ('Precio_mensual', models.IntegerField()),
                ('Meses_actualizacion_IPC', models.IntegerField()),
            ],
        ),
    ]
