# Generated by Django 5.2.4 on 2025-07-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='Dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.dueno'),
        ),
    ]
