# Generated by Django 5.2.4 on 2025-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_dueno_alter_alquiler_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Porcentaje_actualizacion',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
