# Generated by Django 5.2.4 on 2025-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alquiler_porcentaje_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Porcentaje_actualizacion',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
