# Generated by Django 5.2.4 on 2025-08-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_alter_alquiler_porcentaje_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Meses_actualizacion_IPC',
            field=models.IntegerField(blank=True),
        ),
    ]
