# Generated by Django 5.2.4 on 2025-08-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_alter_alquiler_meses_actualizacion_ipc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Meses_actualizacion_IPC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='Porcentaje_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
