# Generated by Django 5.2.4 on 2025-08-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_alter_alquiler_porcentaje_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Porcentaje_actualizacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
