# Generated by Django 5.2.4 on 2025-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_alter_alquiler_porcentaje_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Comentario_ABL',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Comentario_Agua',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Precio_ABL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Precio_Agua',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='Meses_actualizacion_IPC',
            field=models.IntegerField(blank=True),
        ),
    ]
