# Generated by Django 5.2.4 on 2025-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0009_alquiler_comentario_abl_alquiler_comentario_agua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='Comentario_ABL',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='Comentario_Agua',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Observacion',
            field=models.CharField(blank=True),
        ),
    ]
