# Generated by Django 5.2.4 on 2025-08-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0010_remove_alquiler_comentario_abl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='Observacion',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Cancelacion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquiler.metodopago'),
        ),
    ]
