# Generated by Django 5.2.4 on 2025-08-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_metodopago_alter_alquiler_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Precio_ABL',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='Precio_Agua',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
