# Generated by Django 5.2.4 on 2025-08-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0012_alter_alquiler_precio_abl_alter_alquiler_precio_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
