# Generated by Django 5.2.4 on 2025-08-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0013_alter_alquiler_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Observacion',
            field=models.TextField(blank=True, max_length=190, null=True),
        ),
    ]
