# Generated by Django 5.2.4 on 2025-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0014_alter_alquiler_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Precio_Pasto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
