# Generated by Django 5.2.4 on 2025-08-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0015_alquiler_precio_pasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Observacion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
