# Generated by Django 5.2.4 on 2025-08-25 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0017_alter_alquiler_observacion'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
