# Generated by Django 5.2.4 on 2025-09-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0018_alquiler_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dueno',
            name='Apellido',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alias', models.CharField(blank=True, default='')),
                ('Cbu', models.IntegerField(blank=True, default='')),
                ('Titular_cuenta', models.CharField()),
                ('Banco', models.CharField()),
                ('Dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.dueno')),
            ],
        ),
    ]
