# Generated by Django 5.2.4 on 2025-09-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0019_alquiler_ultima_actualizacion_dueno_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='Cbu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
