# Generated by Django 5.2.4 on 2025-09-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0020_alter_datosbancarios_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='Dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_bancarios', to='alquiler.dueno'),
        ),
    ]
