# Generated by Django 5.2.4 on 2025-10-21 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0021_alter_datosbancarios_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='Dueno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_bancarios', to='alquiler.dueno'),
        ),
    ]
