# Generated by Django 5.2.4 on 2025-10-22 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0022_alter_datosbancarios_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='Dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='alquiler.dueno'),
        ),
    ]
