# Generated by Django 5.2.4 on 2025-09-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
